#!/usr/bin/env node


process.env.AWS_PROFILE = "drinkbev";
process.env.tablePrefix = `${process.env.AWS_PROFILE}_`;

const model = require('model');
const Config = model.Config;
const shopify = require('shopify-graphql');

//  const pry = require('pryjs');
/*
subscription,fortyeight,variety,32713888104545,155,0.4,258.33
subscription,fortyeight,rose,37693085745345,155,0.4,258.33
subscription,fortyeight,blanc,37693085089985,155,0.4,258.33
subscription,fortyeight,gris,37693031678145,155,0.4,258.33
subscription,fortyeight,noir,37683735101633,155,0.4,258.33
subscription,fortyeight,glitz,37693083910337,183.08,0.4,305.13
*/



const products = {
  variety: 4583347617889,
  rose: 4555615567969,
  blanc: 4589040402529,
  gris: 4580781686881,
  noir: 6098002936001,
  glitz: 4791953096801
};

const subscriptionproducts = {
  variety: 6131334447297,
  rose: 6131243778241,
  blanc: 6131243450561,
  gris: 6131225723073,
  noir: 6127171567809,
  glitz: 6131242893505
}


const round = (v) => {
  return Math.round(v * 100) / 100.0;
}

const extractSizeFromSku = (sku) => {
  if (sku.match(/24/)) {
    return "twentyfour";
  }

  if (sku.match(/48/)) {
    return "fortyeight"
  }

  if (sku.match(/8/)) {
    return "eight";
  }

}


const calcOriginalPrice = (price, discount) => {
  return round(price / (1.0 - discount))
};

const createRec = (v, discount) => {

  const result = {
    price: Math.ceil(parseFloat(v.price)),
    id: parseFloat(v.id.split("/").slice(-1)[0]),
    discount: discount,
    original_price: parseFloat(v.compareAtPrice || 0)

  };

  return result;

};

const map = async (products, discount) => {
  const result = {};

  for (const [variety, productId] of Object.entries(products)) {
    const product = await shopify.product(shopify.gid("Product", productId));
    const variants = product.product.variants.edges.map(x => x.node);

    for (const v of variants) {

      let size = extractSizeFromSku(v.sku);

      result[size] = result[size] || {};
      result[size][variety] = createRec(v, discount);

      if (size === null) {
        throw Error("Bombs");
      }
    }
  }
  return result;
}

const generateDiscounts = async (discount, productId) => {
  const result = {};
  const product = await shopify.product(shopify.gid("Product", productId));
  const variants = product.product.variants.edges.map(x => x.node);

  for (v of variants) {
    if (v.sku.match(/BEV.*PK/)) {
      const variety = v.title.split(" - ")[1].replace(/^Bev\ /, '').replace("é", "e").replace("Ladies Night", 'Variety').toLowerCase();
      const size = extractSizeFromSku(v.sku);
      result[size] = result[size] || {};
      result[size][variety] = {
        price: parseFloat(v.price),
        id: parseFloat(v.id.split("/").slice(-1)[0]),
        discount: discount,
        original_price: parseFloat(v.compareAtPrice || 0)
      }
    }
  }


  return result;

};


(async function () {
  const config = await Config.fetch();
  shopify.setClient(config.shopify.storeDomain, config.shopify.password);

  const [onetime, subscription] = await Promise.all([
    map(products, 0.20),
    map(subscriptionproducts, 0.40)
  ]);

  const result = {
    onetime,
    subscription,
    discount20: onetime,
    discount25: await generateDiscounts(0.25, 6118304940225), 
  };

  console.log("// Generated by dumpVariants.js, change script not JSON.");
  console.log('(function() {');
  console.log(`const variants = ${JSON.stringify(result, null, 4)}`);
  console.log(`
      if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
        module.exports = variants;
      }
      else {
        if (typeof define === 'function' && define.amd) {
          define([], function() {
            return variants;
          });
        }
        else {
          window.variants = variants;
        }
      }
    })();    
  `);

})();