// Generated by dumpVariants.js, change script not JSON.
(function() {
const variants = {
    "onetime": {
        "twentyfour": {
            "variety": {
                "price": 99,
                "id": 32088206803041,
                "discount": 0.2,
                "original_price": 120
            },
            "rose": {
                "price": 99,
                "id": 32088185995361,
                "discount": 0.2,
                "original_price": 120
            },
            "blanc": {
                "price": 99,
                "id": 32107119214689,
                "discount": 0.2,
                "original_price": 120
            },
            "gris": {
                "price": 99,
                "id": 32079223619681,
                "discount": 0.2,
                "original_price": 120
            },
            "noir": {
                "price": 99,
                "id": 37591174119617,
                "discount": 0.2,
                "original_price": 120
            },
            "glitz": {
                "price": 119,
                "id": 32786816663649,
                "discount": 0.2,
                "original_price": 150
            }
        },
        "fortyeight": {
            "variety": {
                "price": 190,
                "id": 32182586015841,
                "discount": 0.2,
                "original_price": 240
            },
            "rose": {
                "price": 190,
                "id": 37683534692545,
                "discount": 0.2,
                "original_price": 240
            },
            "blanc": {
                "price": 190,
                "id": 37683407978689,
                "discount": 0.2,
                "original_price": 240
            },
            "gris": {
                "price": 190,
                "id": 37683536789697,
                "discount": 0.2,
                "original_price": 240
            },
            "noir": {
                "price": 190,
                "id": 37683525353665,
                "discount": 0.2,
                "original_price": 240
            },
            "glitz": {
                "price": 230,
                "id": 37683520929985,
                "discount": 0.2,
                "original_price": 290
            }
        },
        "eight": {
            "rose": {
                "price": 49,
                "id": 32088194383969,
                "discount": 0.2,
                "original_price": 60
            },
            "blanc": {
                "price": 49,
                "id": 32107119181921,
                "discount": 0.2,
                "original_price": 60
            },
            "gris": {
                "price": 49,
                "id": 32079223586913,
                "discount": 0.2,
                "original_price": 60
            },
            "noir": {
                "price": 49,
                "id": 37591174086849,
                "discount": 0.2,
                "original_price": 60
            },
            "glitz": {
                "price": 59,
                "id": 32786816630881,
                "discount": 0.2,
                "original_price": 75
            }
        }
    },
    "subscription": {
        "twentyfour": {
            "variety": {
                "price": 79,
                "id": 37693274423489,
                "discount": 0.4,
                "original_price": 120
            },
            "rose": {
                "price": 79,
                "id": 37693085679809,
                "discount": 0.4,
                "original_price": 120
            },
            "blanc": {
                "price": 79,
                "id": 37693085057217,
                "discount": 0.4,
                "original_price": 120
            },
            "gris": {
                "price": 79,
                "id": 37693031645377,
                "discount": 0.4,
                "original_price": 120
            },
            "noir": {
                "price": 79,
                "id": 37683735068865,
                "discount": 0.4,
                "original_price": 120
            },
            "glitz": {
                "price": 95,
                "id": 37693083877569,
                "discount": 0.4,
                "original_price": 150
            }
        },
        "fortyeight": {
            "variety": {
                "price": 152,
                "id": 37693274456257,
                "discount": 0.4,
                "original_price": 240
            },
            "rose": {
                "price": 152,
                "id": 37693085745345,
                "discount": 0.4,
                "original_price": 240
            },
            "blanc": {
                "price": 152,
                "id": 37693085089985,
                "discount": 0.4,
                "original_price": 240
            },
            "gris": {
                "price": 152,
                "id": 37693031678145,
                "discount": 0.4,
                "original_price": 240
            },
            "noir": {
                "price": 152,
                "id": 37683735101633,
                "discount": 0.4,
                "original_price": 240
            },
            "glitz": {
                "price": 184,
                "id": 37693083910337,
                "discount": 0.4,
                "original_price": 290
            }
        },
        "eight": {
            "rose": {
                "price": 39,
                "id": 37693085614273,
                "discount": 0.4,
                "original_price": 60
            },
            "blanc": {
                "price": 39,
                "id": 37693085024449,
                "discount": 0.4,
                "original_price": 60
            },
            "gris": {
                "price": 39,
                "id": 37693031612609,
                "discount": 0.4,
                "original_price": 60
            },
            "noir": {
                "price": 39,
                "id": 37683735036097,
                "discount": 0.4,
                "original_price": 60
            },
            "glitz": {
                "price": 47,
                "id": 37693083844801,
                "discount": 0.4,
                "original_price": 75
            }
        }
    },
    "discount20": {
        "twentyfour": {
            "variety": {
                "price": 99,
                "id": 32088206803041,
                "discount": 0.2,
                "original_price": 120
            },
            "rose": {
                "price": 99,
                "id": 32088185995361,
                "discount": 0.2,
                "original_price": 120
            },
            "blanc": {
                "price": 99,
                "id": 32107119214689,
                "discount": 0.2,
                "original_price": 120
            },
            "gris": {
                "price": 99,
                "id": 32079223619681,
                "discount": 0.2,
                "original_price": 120
            },
            "noir": {
                "price": 99,
                "id": 37591174119617,
                "discount": 0.2,
                "original_price": 120
            },
            "glitz": {
                "price": 119,
                "id": 32786816663649,
                "discount": 0.2,
                "original_price": 150
            }
        },
        "fortyeight": {
            "variety": {
                "price": 190,
                "id": 32182586015841,
                "discount": 0.2,
                "original_price": 240
            },
            "rose": {
                "price": 190,
                "id": 37683534692545,
                "discount": 0.2,
                "original_price": 240
            },
            "blanc": {
                "price": 190,
                "id": 37683407978689,
                "discount": 0.2,
                "original_price": 240
            },
            "gris": {
                "price": 190,
                "id": 37683536789697,
                "discount": 0.2,
                "original_price": 240
            },
            "noir": {
                "price": 190,
                "id": 37683525353665,
                "discount": 0.2,
                "original_price": 240
            },
            "glitz": {
                "price": 230,
                "id": 37683520929985,
                "discount": 0.2,
                "original_price": 290
            }
        },
        "eight": {
            "rose": {
                "price": 49,
                "id": 32088194383969,
                "discount": 0.2,
                "original_price": 60
            },
            "blanc": {
                "price": 49,
                "id": 32107119181921,
                "discount": 0.2,
                "original_price": 60
            },
            "gris": {
                "price": 49,
                "id": 32079223586913,
                "discount": 0.2,
                "original_price": 60
            },
            "noir": {
                "price": 49,
                "id": 37591174086849,
                "discount": 0.2,
                "original_price": 60
            },
            "glitz": {
                "price": 59,
                "id": 32786816630881,
                "discount": 0.2,
                "original_price": 75
            }
        }
    },
    "discount25": {
        "eight": {
            "rose": {
                "price": 45,
                "id": 37654232367297,
                "discount": 0.25,
                "original_price": 60
            },
            "blanc": {
                "price": 45,
                "id": 37654249603265,
                "discount": 0.25,
                "original_price": 60
            },
            "gris": {
                "price": 45,
                "id": 37654264217793,
                "discount": 0.25,
                "original_price": 60
            },
            "noir": {
                "price": 45,
                "id": 37654275522753,
                "discount": 0.25,
                "original_price": 60
            },
            "glitz": {
                "price": 55,
                "id": 37654279618753,
                "discount": 0.25,
                "original_price": 75
            }
        },
        "twentyfour": {
            "variety": {
                "price": 90,
                "id": 37654292267201,
                "discount": 0.25,
                "original_price": 120
            },
            "rose": {
                "price": 90,
                "id": 37654295740609,
                "discount": 0.25,
                "original_price": 120
            },
            "blanc": {
                "price": 90,
                "id": 37654308094145,
                "discount": 0.25,
                "original_price": 120
            },
            "gris": {
                "price": 90,
                "id": 37654310256833,
                "discount": 0.25,
                "original_price": 120
            },
            "noir": {
                "price": 90,
                "id": 37654315204801,
                "discount": 0.25,
                "original_price": 120
            },
            "glitz": {
                "price": 109,
                "id": 37654325985473,
                "discount": 0.25,
                "original_price": 150
            }
        },
        "fortyeight": {
            "variety": {
                "price": 180,
                "id": 37654327492801,
                "discount": 0.25,
                "original_price": 240
            },
            "rose": {
                "price": 180,
                "id": 37654336143553,
                "discount": 0.25,
                "original_price": 240
            },
            "blanc": {
                "price": 180,
                "id": 37654349545665,
                "discount": 0.25,
                "original_price": 240
            },
            "gris": {
                "price": 180,
                "id": 37654353838273,
                "discount": 0.25,
                "original_price": 240
            },
            "noir": {
                "price": 180,
                "id": 37654354624705,
                "discount": 0.25,
                "original_price": 240
            },
            "glitz": {
                "price": 215,
                "id": 37654357049537,
                "discount": 0.25,
                "original_price": 290
            }
        }
    }
}

      if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
        module.exports = variants;
      }
      else {
        if (typeof define === 'function' && define.amd) {
          define([], function() {
            return variants;
          });
        }
        else {
          window.variants = variants;
        }
      }
    })();    
  
